[device]
name = "\\\\.\\TestDriver"

[[ioctl]]
name = "IOCTL_1"
code = 0x220004
input_buffer_size = 64
output_buffer_size = 128
# Input buffer content: hex string
input_buffer_content = [
     { offset = 0x30, type = "u32", value = 0x41414141}
]

[[ioctl]]
name = "IOCTL_2"
code = 0x220008
input_buffer_size = 32
output_buffer_size = 64
# More complex buffer specification (see next section)
input_buffer_content = [
    { offset = 0, type = "hex", value = "DEADC0DE" },
    { offset = 4, type = "u32", value = 12345 },
    { offset = 8, type = "fill", value = 0, length = 24 } # Fill remaining 24 bytes with 0
]

[[ioctl]]
name = "IOCTL_3"
code = 0x22000C
input_buffer_size = 0
output_buffer_size = 256
